
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author elisc
 */
public class WetterWerteGUI extends javax.swing.JFrame {

    private WetterModell bl = new WetterModell();

    /**
     * Creates new form WetterWerteGUI
     */
    public WetterWerteGUI() {
        initComponents();
        ltOut.setModel(bl);
        sdMoisture.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent event) {
                int value = sdMoisture.getValue();
                lbMoisture.setText(String.format("Luftfeuchtigkeit: %d", value) + "%");
            }
        });
        sdTemp.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent event) {
                int value = sdTemp.getValue();
                lbTemp.setText(String.format("Temperatur: %d° C", value));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame2 = new javax.swing.JInternalFrame();
        lbTemp = new javax.swing.JLabel();
        sdTemp = new javax.swing.JSlider();
        lbMoisture = new javax.swing.JLabel();
        sdMoisture = new javax.swing.JSlider();
        btAdd = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        ltOut = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jInternalFrame2.setTitle("Eingabe");
        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(new java.awt.GridLayout(5, 0));

        lbTemp.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbTemp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTemp.setText("Temperatur: 0° C");
        lbTemp.setToolTipText("");
        jInternalFrame2.getContentPane().add(lbTemp);

        sdTemp.setMajorTickSpacing(10);
        sdTemp.setMaximum(40);
        sdTemp.setMinimum(-20);
        sdTemp.setMinorTickSpacing(5);
        sdTemp.setPaintLabels(true);
        sdTemp.setPaintTicks(true);
        sdTemp.setValue(0);
        jInternalFrame2.getContentPane().add(sdTemp);

        lbMoisture.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbMoisture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMoisture.setText("Luftfeuchtigkeit: 50%");
        jInternalFrame2.getContentPane().add(lbMoisture);

        sdMoisture.setMajorTickSpacing(10);
        sdMoisture.setMinorTickSpacing(5);
        sdMoisture.setPaintLabels(true);
        sdMoisture.setPaintTicks(true);
        jInternalFrame2.getContentPane().add(sdMoisture);

        btAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAdd.setText("Einfügen");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btAdd);

        getContentPane().add(jInternalFrame2);

        jInternalFrame1.setTitle("Anzeige");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        ltOut.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ltOut);

        jInternalFrame1.getContentPane().add(jScrollPane1);

        getContentPane().add(jInternalFrame1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        String tempstr = lbTemp.getText();
        int temp = Integer.parseInt(tempstr.substring(tempstr.indexOf(" ") + 1, tempstr.indexOf("°")));
        String moisturestr = lbMoisture.getText();
        int moisture
                = Integer
                        .parseInt(moisturestr.substring(moisturestr.indexOf(" ") + 1, moisturestr.indexOf("%")));
        WetterWert wert
                = new WetterWert(temp, moisture,
                        LocalDateTime.now());
        bl.add(wert);
    }//GEN-LAST:event_btAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WetterWerteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WetterWerteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WetterWerteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WetterWerteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WetterWerteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMoisture;
    private javax.swing.JLabel lbTemp;
    private javax.swing.JList<String> ltOut;
    private javax.swing.JSlider sdMoisture;
    private javax.swing.JSlider sdTemp;
    // End of variables declaration//GEN-END:variables
}
